### ISSUE TITLE
Getting an error with VstsTaskSdk

### ISSUE THREAD

**Issue by paulkatich** [pwshliquori/azuredevops-extension-run-oracle-scripts#1]
When I run the task I am getting below file not found error for the oracle scripts task.

2019-04-15T17:31:28.4129410Z ##[error]File not found: 'C:\agent\_work\_tasks\RunOracleScripts_cde17640-4d22-410e-ae92-83ae8542e41c\1.0.1\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'

**Comment by paulkatich** [comment]
@pwshliquori  Can you please look in to this ?

**Comment by liquorichris** [comment]
Vstssdk was removed from the repo. Added it back. Can you give a try now please?

Fixed on commit: 15e53e331f719fed6a03940ccda4addd66162a5f

**Comment by paulkatich** [comment]
Thank you @pwshliquori . It works now. The task doesnt stop on error. I pointed the task to look at a folder that has a simple create restore point script. The create restore point fails "ERROR at line 1:
  ORA-38778: Restore point 'TEST_RESTOREPOINT' already exists.". I have the "Exit on sqlerror" checked in sql options. Do I need manually pass the error code by raising  in a begin - end block ?

**Comment by liquorichris** [comment]
Thanks for the update. I will open up a new issue about this and work on it.
