### ISSUE TITLE
Document on how to implement this into build pipline azure.

### ISSUE THREAD

**Issue by macupryk** [pwshliquori/azuredevops-extension-run-oracle-scripts#11]
Hi Team,

Just wondering if you have any documentation on how to implement this in azure build pipeline?

Thank you

**Comment by liquorichris** [comment]
Hello,

You would just install the extension in Azure DevOps and add the task to your build pipeline. After adding the task, you fill out the parameters required for your scripts to run.

https://learn.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser

https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/yaml-pipeline-editor?view=azure-devops

**Comment by macupryk** [comment]
should I install these 2 extensions?
![image](https://github.com/LiquoriChris/azuredevops-extension-run-oracle-scripts/assets/8411821/4d276484-a465-4325-9778-1e1ad35bd830)

**Comment by liquorichris** [comment]
No, you only need the first one. The second one is if you want to develop a custom extension.

**Comment by macupryk** [comment]
If I want to run oracle sql scripts should I create a release pipeline? how do incorporate this in pipeline?

**Comment by liquorichris** [comment]
That would up to you and if you’re working with colleagues. Usually I have
set it up as part of a release pipeline and run the task after I deploy the
code base.

**Comment by macupryk** [comment]
![image](https://github.com/LiquoriChris/azuredevops-extension-run-oracle-scripts/assets/8411821/f2afc055-aa70-41af-af2a-a5da0827e8c7)

**Comment by liquorichris** [comment]
When you add the task, there are a number of fields to fill out pertaining to your db, script paths, etc.

**Comment by macupryk** [comment]
I see that is great news. I will try this out in a few days and let you know how it goes. This is very great extension.

**Comment by macupryk** [comment]
Hi Chris, Is the database name the host name?
do I just put a sql file in repo? do you have example of sql file?
Is this ok?
![image](https://github.com/LiquoriChris/azuredevops-extension-run-oracle-scripts/assets/8411821/26fce09f-bd32-4c79-bf66-f2bf4493a741)

**Comment by macupryk** [comment]
I am getting this error:
![image](https://github.com/LiquoriChris/azuredevops-extension-run-oracle-scripts/assets/8411821/ca33cec6-1962-44ce-a097-7d54b11592f4)
