### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by gopalramadugu** [pwshliquori/azuredevops-extension-run-oracle-scripts#3]
Fail on missing scripts. Can we please have a check box in sql options or some other group that allows the task to fail if the folder is missing files. 

@pwshliquori

**Comment by liquorichris** [comment]
Will be adding this feature tomorrow. @gopalramadugu Please be aware, I needed to change the publisher of which the extension runs under. You will need to remove and re-install the extension after I add the feature. Sorry for any inconvenience.

**Comment by liquorichris** [comment]
Feature has been added. Moved "Fail on ora- error" and "Fail on missing sql files" to new group: Advanced.

Please remember to remove and reinstall the extension as I needed to move the extension to a new publisher.

Commit: 96e321e81ce46ecd3c51ffb463b00af334c527a1
