### ISSUE TITLE
Working with Azure Devops

### ISSUE THREAD

**Issue by Rajkumar1988** [pwshliquori/azuredevops-extension-run-oracle-scripts#4]
Hi,

I installed the plugin onto my Azure Devops organization. Can you pls. help me to understand how do I use it in my build pipeline to run a create table query?

Regards
Raj

**Comment by liquorichris** [comment]
I have only scoped this extension to run in the release pipeline, I will add build pipeline support.

**Comment by liquorichris** [comment]
Build pipeline visibility added with commit: 69ae1051d75f31cb4ba529543904ee2a3adf73a6

**Comment by Rajkumar1988** [comment]
Thanks a lot mate. I can see now in build tasks. 
I am not from database/oracle background hence the below questions, will really appreciate if you can help :)
1. Will Microsoft agents work or should I have to create self hosted agents with SQLplus installed?
2. Is there a way to create connection strings to different oracle databases in case of Microsoft agents?
3. How does this plugin understand which DB to connect in case of Microsoft agents with just database name?
4. Will this plugin support Oracle cloud?

Regards
Raj

**Comment by sanakanchha** [comment]
@Rajkumar1988 I am in the same boat and just came across this feed. Were you able to solve this? I created the self-hosted agent which runs in the same subnet as theOracle DB. Is the plugin able to understand which DB to connect with just the DB name?

**Comment by Rajkumar1988** [comment]
@sanakanchha , that plug-in is depreciated . In my opinion azure devops is not a wise choice for oracle deployments . 

Try flexagon.

**Comment by sanakanchha** [comment]
@Rajkumar1988 really appreciate your input. Will check it out, thanks.
