### ISSUE TITLE
SQL plus

### ISSUE THREAD

**Issue by PolinaIva** [pwshliquori/azuredevops-extension-run-oracle-scripts#7]
When I tried to launch pipeline with this extension, it was failed with this error: "No agent found in pool ... which satisfies the specified demands: sqlplus.exe". It seems to me that this extension tried to load the sql plus on my computer, but I thought that pipeline should load it on the db, that is not on my local pc. Can you explain me what is the problem and how I can solve it?

**Comment by sunil-pawar** [comment]
@PolinaIva  you need to mannually add the capability under your agent sqlplus.exe and value the path of the sqlplus.exe file

**Comment by liquorichris** [comment]
That’s correct. There is a dependency I have setup in the task to verify sqlplus is installed.
